---
name: Add review url

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add comment to PR
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          prnumber="$(basename $(dirname ${{GITHUB_REF}}))"
          gh release create "$tagname" *.png
          gh pr comment ${prnumber} -b "Review latest: http://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/${github.repository}}/${{github.ref_name}}/latest/index.bs"
